config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
   #get 'home/index'
   get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
belongs_to :user 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :friends 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build

  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
     @friend = current_user.friends.build(friend_params) 
    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


def correct_user
  @friend = current_user.friends.find_by(id: params[:id])
  redirect_to friends_path, notice:"Not Authorized to edit this friend" if @friend.nil?  
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :eamil, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def about
    @about_me = "My name is praveen"
    @answer = 2 + 2


  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
<br/>
  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>
  </div>
<br/>
  <div class="field form-group">
    
    <%= form.text_field :eamil, class:"form-control", placeholder:"E-mail"  %>
  </div>
<br/>
  <div class="field form-group">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
  </div>
<br/>
  <div class="field form-group">
    
    <%= form.text_field :twitter, class:"form-control", placeholder:"twitter account" %>
  </div>
<br/>

<div class="field form-group">
    
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  


  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %> 

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger " %>

<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/index.html.erb
<% if user_signed_in?
%>

<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">

    <tr>
      <th>Name</th>
      
      <th>Eamil</th>
      <th>Phone</th>
      <th>Twitter</th>
      
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>

    <% if friend.user == current_user%>
      <tr>
      <td>
        <%= link_to friend.first_name + ' '+ friend.last_name,
        friend %>
        
      </td>
        <td><%= friend.eamil %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        

        
        
        <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
 </tr>
  <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>

<% else %>
<h1>Hello World</h1>
This is my first rails webpage
<% end %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead"><%= @friend.eamil %> |
    <%= @friend.phone %> | <%= @friend.twitter %>
  </p>
  
  <br/><br/>
  
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %> 

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger " %>
  
<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

</div>
 

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'Friend App', root_path, class: "navbar-brand" %>
     
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
          <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" %>
          </li>

          

        

        <% if user_signed_in? %>

            <li class="nav-item"> 
              <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>        
            </li> 

            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li> 

            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
            </li>  

        <% else %>

            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li> 

            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li> 

        <% end %>

        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav> 

app/views/home/about.html.erb
<h1> About us </h1>

<p>
	<%= @about_me %>
</p>

<p>
	2+2 = <%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first rails webpage

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Friends App</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header'%>

    <div class="container">
      <br/>

      <% if notice %>
        <%= render 'layouts/alerts' %>
        <% end %>

      <br/>

       
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>